name: Update PBF file and tiles

on:
  #schedule:
  #  - cron: '0 * * * *'
  push:
    tags: 
      - update.*

jobs:
  generate-tiles:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tokenless-tiles/template:1.1.0
      credentials:
        username: typebrook
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Load environment variables
        run: cat .env >>$GITHUB_ENV && ls -alh

      - name: Get target PBF file
        env:
          REPO: ${{ github.repository }}
          TOKEN_DOWNLOAD_ARTIFACT: ${{ secrets.TOKEN_DOWNLOAD_ARTIFACT }}
        run: ./get-pbf-file.sh
      
      - name: Generate Tiles
        run: >
          tilemaker --input ${{ env.TARGET }} --output tiles/
          --config  ${{ env.TILEMAKER_CONFIG }}
          --process ${{ env.TILEMAKER_PROCESS }}

      - name: Commit newly-generated tiles
        run: > 
          git config --local user.email "typebrook@gmail.com";
          git config --local user.name "typebrook";
          [ -n "$(git status tiles/ --short)" ]
          && git branch gh-pages
          && git checkout gh-pages
          && git add tiles/* >/dev/null
          && git commit -m 'update'
          && git push --force --set-upstream origin gh-pages
          || true
      
      - name: Upload updated PBF file as artifact for next workflow run
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}
          path: ${{ github.workspace }}/${{ env.TARGET }}

      - run: find tiles/ -name '*.pbf' >tiles.list
      - name: Make list of tiles
        uses: actions/upload-artifact@v2
        with:
          name: tiles.list
          path: ${{ github.workspace }}/tiles.list
